// AUTO-GENERATED by scripts/generate_tokens.py — DO NOT EDIT.
// 唯一规范源：shared/design-system.yaml

export type ThemeName = keyof typeof THEMES;

export const THEMES = {"default": {"colors": {"primary": "#0052D9", "secondary": "#7C4DFF", "danger": "#E5352B", "success": "#00A870", "background": "#F5F5F5", "text-primary": "#1D2129", "text-secondary": "#4E5969", "text-light": "#86909C", "border": "#E5E8EF"}, "typography": {"heading": {"font": "Inter", "weight": 600, "size": 24}, "body": {"font": "Inter", "weight": 400, "size": 14}, "caption": {"font": "Inter", "weight": 400, "size": 12}}, "spacing": {"xs": 4, "sm": 8, "md": 16, "lg": 24, "xl": 32}, "radius": {"sm": 4, "md": 8, "lg": 12}}, "dark": {"colors": {"primary": "#3D7FFF", "secondary": "#9578FF", "danger": "#F2645A", "success": "#35C08E", "background": "#14161A", "text-primary": "#E6E8EB", "text-secondary": "#A8B0BC", "text-light": "#6B7280", "border": "#2A2E36"}, "typography": {"heading": {"font": "Inter", "weight": 600, "size": 24}, "body": {"font": "Inter", "weight": 400, "size": 14}, "caption": {"font": "Inter", "weight": 400, "size": 12}}, "spacing": {"xs": 4, "sm": 8, "md": 16, "lg": 24, "xl": 32}, "radius": {"sm": 4, "md": 8, "lg": 12}}} as const;

export const ALLOWED_HEX_COLORS: readonly string[] = ["#FF6B6B", "#FFFFFF", "#000000", "#FFF0F0", "#FF6B35"];

/** 取令牌色值；不存在返回 undefined */
export function colorValue(theme: ThemeName, token: string): string | undefined {
  const colors = THEMES[theme]?.colors as Record<string, string> | undefined;
  return colors?.[token];
}

/** 合规检查：值是否为令牌色值或白名单 hex（hex 大小写不敏感） */
export function isAllowedColor(theme: ThemeName, value: string): boolean {
  const v = value.startsWith('#') ? value.toUpperCase() : value;
  if ((ALLOWED_HEX_COLORS as readonly string[]).some((c) => c.toUpperCase() === v)) return true;
  const colors = THEMES[theme]?.colors as Record<string, string> | undefined;
  if (!colors) return false;
  for (const [token, hexv] of Object.entries(colors)) {
    if (v === hexv.toUpperCase() || v === token) return true;
  }
  return false;
}

/** 违规色值拉回最近令牌（按十六进制距离），返回令牌名 */
export function nearestToken(theme: ThemeName, value: string): string {
  const colors = THEMES[theme]?.colors as Record<string, string> | undefined;
  if (!colors) return 'primary';
  const parse = (hex: string) => [parseInt(hex.slice(1, 3), 16), parseInt(hex.slice(3, 5), 16), parseInt(hex.slice(5, 7), 16)];
  let best = 'primary', bestDist = Infinity;
  const target = /^#[0-9a-fA-F]{6}$/.test(value) ? parse(value) : null;
  if (!target) return best;
  for (const [token, hexv] of Object.entries(colors)) {
    const [r, g, b] = parse(hexv);
    const dist = (target[0] - r) ** 2 + (target[1] - g) ** 2 + (target[2] - b) ** 2;
    if (dist < bestDist) { best = token; bestDist = dist; }
  }
  return best;
}
