# AUTO-GENERATED by scripts/generate_tokens.py — DO NOT EDIT.
# 唯一规范源：shared/design-system.yaml

THEMES: dict = ["default", "dark"]

COLORS: dict = {"default": {"primary": "#0052D9", "secondary": "#7C4DFF", "danger": "#D32029", "success": "#00A870", "background": "#F5F5F5", "text-primary": "#1D2129", "text-secondary": "#4E5969", "text-light": "#5F6B7A", "border": "#E5E8EF"}, "dark": {"primary": "#3D7FFF", "secondary": "#9578FF", "danger": "#F2645A", "success": "#35C08E", "background": "#14161A", "text-primary": "#E6E8EB", "text-secondary": "#A8B0BC", "text-light": "#6B7280", "border": "#2A2E36"}}
TYPOGRAPHY: dict = {"default": {"heading": {"font": "Inter", "weight": 600, "size": 24}, "body": {"font": "Inter", "weight": 400, "size": 14}, "caption": {"font": "Inter", "weight": 400, "size": 12}}, "dark": {"heading": {"font": "Inter", "weight": 600, "size": 24}, "body": {"font": "Inter", "weight": 400, "size": 14}, "caption": {"font": "Inter", "weight": 400, "size": 12}}}
SPACING: dict = {"default": {"xs": 4, "sm": 8, "md": 16, "lg": 24, "xl": 32}, "dark": {"xs": 4, "sm": 8, "md": 16, "lg": 24, "xl": 32}}
RADIUS: dict = {"default": {"sm": 4, "md": 8, "lg": 12}, "dark": {"sm": 4, "md": 8, "lg": 12}}
ALLOWED_HEX_COLORS: list = ["#FF6B6B", "#FFFFFF", "#000000", "#FFF0F0", "#FF6B35"]


def color_value(theme: str, token: str) -> str | None:
    """取令牌色值；不存在返回 None。"""
    return COLORS.get(theme, {}).get(token)


def is_allowed_color(theme: str, value: str) -> bool:
    """合规检查：值是否为令牌色值或白名单 hex（hex 大小写不敏感）。"""
    v = value.upper() if value.startswith("#") else value
    if v in [c.upper() for c in ALLOWED_HEX_COLORS]:
        return True
    for token, hexv in COLORS.get(theme, {}).items():
        if v == hexv.upper() or v == token:
            return True
    return False


def nearest_token(theme: str, value: str) -> str:
    """违规色值拉回最近令牌（按十六进制距离），返回令牌名。"""
    best, best_dist = "primary", 1 << 30
    try:
        r, g, b = int(value[1:3], 16), int(value[3:5], 16), int(value[5:7], 16)
    except (ValueError, IndexError):
        return best
    for token, hexv in COLORS.get(theme, {}).items():
        rr, gg, bb = int(hexv[1:3], 16), int(hexv[3:5], 16), int(hexv[5:7], 16)
        dist = (r - rr) ** 2 + (g - gg) ** 2 + (b - bb) ** 2
        if dist < best_dist:
            best, best_dist = token, dist
    return best
