#!/usr/bin/env python3
"""从 shared/design-system.yaml 生成双端令牌常量。

产出：
- backend/app/design/tokens.py        （Python 常量 + 查询函数）
- frontend/src/design/tokens.generated.ts （TS 常量 + 查询函数）

用法：python scripts/generate_tokens.py
运行后必须两端测试通过（pytest + vitest 各有一个"令牌与生成物一致"的用例）。
"""
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SHARED = ROOT / "shared"
OUT_BACKEND = ROOT / "backend" / "app" / "design"
OUT_FRONTEND = ROOT / "frontend" / "src" / "design"


def load() -> dict:
    with open(SHARED / "design-system.yaml", encoding="utf-8") as f:
        return yaml.safe_load(f)


def write_python(data: dict) -> None:
    OUT_BACKEND.mkdir(parents=True, exist_ok=True)
    colors = {t: data["themes"][t]["colors"] for t in data["themes"]}
    typos = {t: data["themes"][t]["typography"] for t in data["themes"]}
    spacing = {t: data["themes"][t]["spacing"] for t in data["themes"]}
    radius = {t: data["themes"][t]["radius"] for t in data["themes"]}
    allowed = data.get("allowed_hex_colors", [])
    content = f'''# AUTO-GENERATED by scripts/generate_tokens.py — DO NOT EDIT.
# 唯一规范源：shared/design-system.yaml

THEMES: dict = {json.dumps(list(data["themes"].keys()), ensure_ascii=False)}

COLORS: dict = {json.dumps(colors, ensure_ascii=False)}
TYPOGRAPHY: dict = {json.dumps(typos, ensure_ascii=False)}
SPACING: dict = {json.dumps(spacing, ensure_ascii=False)}
RADIUS: dict = {json.dumps(radius, ensure_ascii=False)}
ALLOWED_HEX_COLORS: list = {json.dumps(allowed, ensure_ascii=False)}


def color_value(theme: str, token: str) -> str | None:
    """取令牌色值；不存在返回 None。"""
    return COLORS.get(theme, {{}}).get(token)


def is_allowed_color(theme: str, value: str) -> bool:
    """合规检查：值是否为令牌色值或白名单 hex（hex 大小写不敏感）。"""
    v = value.upper() if value.startswith("#") else value
    if v in [c.upper() for c in ALLOWED_HEX_COLORS]:
        return True
    for token, hexv in COLORS.get(theme, {{}}).items():
        if v == hexv.upper() or v == token:
            return True
    return False


def nearest_token(theme: str, value: str) -> str:
    """违规色值拉回最近令牌（按十六进制距离），返回令牌名。"""
    best, best_dist = "primary", 1 << 30
    try:
        r, g, b = int(value[1:3], 16), int(value[3:5], 16), int(value[5:7], 16)
    except (ValueError, IndexError):
        return best
    for token, hexv in COLORS.get(theme, {{}}).items():
        rr, gg, bb = int(hexv[1:3], 16), int(hexv[3:5], 16), int(hexv[5:7], 16)
        dist = (r - rr) ** 2 + (g - gg) ** 2 + (b - bb) ** 2
        if dist < best_dist:
            best, best_dist = token, dist
    return best
'''
    (OUT_BACKEND / "tokens.py").write_text(content, encoding="utf-8")
    print(f"[gen] backend/app/design/tokens.py ({len(content)} chars)")


def write_typescript(data: dict) -> None:
    OUT_FRONTEND.mkdir(parents=True, exist_ok=True)
    themes = json.dumps(data["themes"], ensure_ascii=False)
    allowed = json.dumps(data.get("allowed_hex_colors", []), ensure_ascii=False)
    content = f'''// AUTO-GENERATED by scripts/generate_tokens.py — DO NOT EDIT.
// 唯一规范源：shared/design-system.yaml

export type ThemeName = keyof typeof THEMES;

export const THEMES = {themes} as const;

export const ALLOWED_HEX_COLORS: readonly string[] = {allowed};

/** 取令牌色值；不存在返回 undefined */
export function colorValue(theme: ThemeName, token: string): string | undefined {{
  const colors = THEMES[theme]?.colors as Record<string, string> | undefined;
  return colors?.[token];
}}

/** 合规检查：值是否为令牌色值或白名单 hex（hex 大小写不敏感） */
export function isAllowedColor(theme: ThemeName, value: string): boolean {{
  const v = value.startsWith('#') ? value.toUpperCase() : value;
  if ((ALLOWED_HEX_COLORS as readonly string[]).some((c) => c.toUpperCase() === v)) return true;
  const colors = THEMES[theme]?.colors as Record<string, string> | undefined;
  if (!colors) return false;
  for (const [token, hexv] of Object.entries(colors)) {{
    if (v === hexv.toUpperCase() || v === token) return true;
  }}
  return false;
}}

/** 违规色值拉回最近令牌（按十六进制距离），返回令牌名 */
export function nearestToken(theme: ThemeName, value: string): string {{
  const colors = THEMES[theme]?.colors as Record<string, string> | undefined;
  if (!colors) return 'primary';
  const parse = (hex: string) => [parseInt(hex.slice(1, 3), 16), parseInt(hex.slice(3, 5), 16), parseInt(hex.slice(5, 7), 16)];
  let best = 'primary', bestDist = Infinity;
  const target = /^#[0-9a-fA-F]{{6}}$/.test(value) ? parse(value) : null;
  if (!target) return best;
  for (const [token, hexv] of Object.entries(colors)) {{
    const [r, g, b] = parse(hexv);
    const dist = (target[0] - r) ** 2 + (target[1] - g) ** 2 + (target[2] - b) ** 2;
    if (dist < bestDist) {{ best = token; bestDist = dist; }}
  }}
  return best;
}}
'''
    (OUT_FRONTEND / "tokens.generated.ts").write_text(content, encoding="utf-8")
    print(f"[gen] frontend/src/design/tokens.generated.ts ({len(content)} chars)")


def main() -> None:
    data = load()
    write_python(data)
    write_typescript(data)
    print("[gen] done. Run: backend pytest + frontend vitest")


if __name__ == "__main__":
    sys.exit(main())
